"""Polyglot SQL — Rust-powered SQL transpiler for more than 30 SQL dialects."""

from polyglot_sql._polyglot_sql import (
    Expression,
    ColumnResolutionError,
    GenerateError,
    ParseError,
    PolyglotError,
    TranspileError,
    ValidationError,
    ValidationErrorInfo,
    ValidationResult,
    _builder_builtin,
    alias_,
    analyze_query,
    and_,
    case,
    col,
    column,
    condition,
    convert,
    delete,
    dialects,
    diff,
    format_sql,
    from_,
    func,
    generate,
    lineage,
    lineage_at,
    lineage_at_with_schema,
    lineage_with_schema,
    insert,
    intersect,
    lit,
    merge_into,
    not_,
    output_columns,
    output_columns_with_schema,
    openlineage_column_lineage,
    openlineage_job_event,
    openlineage_run_event,
    optimize,
    or_,
    parse,
    parse_data_type,
    parse_one,
    qualify_tables,
    rename_tables,
    set_limit,
    set_offset,
    set_order_by,
    source_tables,
    select,
    table_,
    tokenize,
    transpile,
    union,
    update,
    except_,
    extract,
    validate,
    version as _version,
)


def _builtin(name, *args):
    return _builder_builtin(name, *args)


def count(expression):
    return _builtin("count", expression)


def count_star():
    return _builtin("count_star")


def count_distinct(expression):
    return _builtin("count_distinct", expression)


def sum_(expression):
    return _builtin("sum", expression)


def avg(expression):
    return _builtin("avg", expression)


def min_(expression):
    return _builtin("min", expression)


def max_(expression):
    return _builtin("max", expression)


def approx_distinct(expression):
    return _builtin("approx_distinct", expression)


def upper(expression):
    return _builtin("upper", expression)


def lower(expression):
    return _builtin("lower", expression)


def length(expression):
    return _builtin("length", expression)


def trim(expression):
    return _builtin("trim", expression)


def ltrim(expression):
    return _builtin("ltrim", expression)


def rtrim(expression):
    return _builtin("rtrim", expression)


def reverse(expression):
    return _builtin("reverse", expression)


def initcap(expression):
    return _builtin("initcap", expression)


def substring(expression, start, length=None):
    if length is None:
        return _builtin("substring", expression, start)
    return _builtin("substring", expression, start, length)


def replace_(expression, old, new):
    return _builtin("replace", expression, old, new)


def concat_ws(separator, *expressions):
    return _builtin("concat_ws", separator, *expressions)


def coalesce(*expressions):
    return _builtin("coalesce", *expressions)


def null_if(left, right):
    return _builtin("null_if", left, right)


def if_null(expression, fallback):
    return _builtin("if_null", expression, fallback)


def abs_(expression):
    return _builtin("abs", expression)


def round_(expression, decimals=None):
    if decimals is None:
        return _builtin("round", expression)
    return _builtin("round", expression, decimals)


def floor(expression):
    return _builtin("floor", expression)


def ceil(expression):
    return _builtin("ceil", expression)


def power(base, exponent):
    return _builtin("power", base, exponent)


def sqrt(expression):
    return _builtin("sqrt", expression)


def ln(expression):
    return _builtin("ln", expression)


def exp(expression):
    return _builtin("exp", expression)


def sign(expression):
    return _builtin("sign", expression)


def greatest(*expressions):
    return _builtin("greatest", *expressions)


def least(*expressions):
    return _builtin("least", *expressions)


def current_date():
    return _builtin("current_date")


def current_time():
    return _builtin("current_time")


def current_timestamp():
    return _builtin("current_timestamp")


def row_number():
    return _builtin("row_number")


def rank():
    return _builtin("rank")


def dense_rank():
    return _builtin("dense_rank")

# Expression subclasses — import all from native module
from polyglot_sql._polyglot_sql import (
    Abs,
    Add,
    AddMonths,
    AddPartition,
    Adjacent,
    AggregateFunction,
    AIAgg,
    AIClassify,
    AlgorithmProperty,
    Alias,
    Aliases,
    All,
    AllowedValuesProperty,
    AlterColumn,
    AlterIndex,
    AlterSequence,
    AlterSession,
    AlterSet,
    AlterSortKey,
    AlterTable,
    AlterView,
    Analyze,
    AnalyzeDelete,
    AnalyzeHistogram,
    AnalyzeListChainedRows,
    AnalyzeSample,
    AnalyzeStatistics,
    AnalyzeValidate,
    AnalyzeWith,
    And,
    Annotated,
    Anonymous,
    AnonymousAggFunc,
    Any,
    AnyValue,
    Apply,
    ApproxCountDistinct,
    ApproxDistinct,
    ApproxPercentile,
    ApproxPercentileEstimate,
    ApproxQuantile,
    ApproxQuantiles,
    ApproxTopK,
    ApproxTopKAccumulate,
    ApproxTopKCombine,
    ApproxTopKEstimate,
    ApproxTopSum,
    ArgMax,
    ArgMin,
    Array,
    ArrayAgg,
    ArrayAll,
    ArrayAny,
    ArrayAppend,
    ArrayCompact,
    ArrayConcat,
    ArrayConcatAgg,
    ArrayConstructCompact,
    ArrayContainedBy,
    ArrayContains,
    ArrayContainsAll,
    ArrayDistinct,
    ArrayExcept,
    ArrayFilter,
    ArrayFlatten,
    ArrayFunc,
    ArrayIntersect,
    ArrayJoin,
    ArrayLength,
    ArrayOverlaps,
    ArrayPosition,
    ArrayPrepend,
    ArrayRemove,
    ArrayReverse,
    ArraySize,
    ArraySlice,
    ArraySort,
    ArraySum,
    ArrayToString,
    ArrayTransform,
    ArrayUnion,
    ArrayUniqueAgg,
    ArrayZip,
    Ascii,
    Asin,
    Acos,
    AssumeColumnConstraint,
    Atan,
    Atan2,
    AtIndex,
    AtTimeZone,
    Attach,
    AttachOption,
    AutoIncrementColumnConstraint,
    AutoIncrementProperty,
    AutoRefreshProperty,
    Avg,
    BackupProperty,
    Base64DecodeBinary,
    Base64DecodeString,
    Base64Encode,
    Between,
    BitwiseAnd,
    BitwiseAndAgg,
    BitwiseCount,
    BitwiseLeftShift,
    BitwiseNot,
    BitwiseOr,
    BitwiseOrAgg,
    BitwiseRightShift,
    BitwiseXor,
    BitwiseXorAgg,
    BlockCompressionProperty,
    BoolXorAgg,
    Boolean,
    Booland,
    Boolor,
    BracedWildcard,
    BuildProperty,
    ByteLength,
    ByteString,
    Cache,
    Cardinality,
    Case,
    CaseSpecificColumnConstraint,
    Cast,
    CastToStrType,
    Cbrt,
    Ceil,
    Changes,
    CharFunc,
    CharacterSetColumnConstraint,
    CharacterSetProperty,
    CheckColumnConstraint,
    CheckJson,
    CheckXml,
    ChecksumProperty,
    Chr,
    Clone,
    ClusterBy,
    ClusterByColumnsProperty,
    ClusteredByProperty,
    Coalesce,
    Collation,
    CollateProperty,
    Column,
    ColumnConstraint,
    ColumnDef,
    ColumnPosition,
    ColumnPrefix,
    Columns,
    CombinedAggFunc,
    CombinedParameterizedAgg,
    Command,
    Comment,
    CommentColumnConstraint,
    Commit,
    Comprehension,
    Compress,
    CompressColumnConstraint,
    ComputedColumnConstraint,
    Concat,
    ConcatWs,
    ConditionalInsert,
    Connect,
    ConnectByRoot,
    Constraint,
    Contains,
    Convert,
    ConvertTimezone,
    ConvertToCharset,
    Copy,
    CopyParameter,
    Corr,
    Cos,
    CosineDistance,
    Count,
    CountIf,
    CovarPop,
    CovarSamp,
    CreateDatabase,
    CreateFunction,
    CreateIndex,
    CreateProcedure,
    CreateSchema,
    CreateSequence,
    CreateTable,
    CreateTrigger,
    CreateType,
    CreateView,
    FlashbackTable,
    Credentials,
    CredentialsProperty,
    Cte,
    Cube,
    CumeDist,
    CurrentDate,
    CurrentDatetime,
    CurrentSchema,
    CurrentSchemas,
    CurrentTime,
    CurrentTimestamp,
    CurrentTimestampLTZ,
    CurrentUser,
    DPipe,
    DataBlocksizeProperty,
    DataDeletionProperty,
    DataType,
    Date,
    DateAdd,
    DateBin,
    DateDiff,
    DateFormat,
    DateFormatColumnConstraint,
    DateFromParts,
    DateFromUnixDate,
    DateStrToDate,
    DateSub,
    DateToDateStr,
    DateToDi,
    DateTrunc,
    Datetime,
    DatetimeAdd,
    DatetimeDiff,
    DatetimeSub,
    DatetimeTrunc,
    Day,
    DayOfMonth,
    DayOfWeek,
    DayOfWeekIso,
    DayOfYear,
    Dayname,
    Declare,
    DeclareItem,
    Decode,
    DecodeCase,
    DecompressBinary,
    DecompressString,
    Decrypt,
    DecryptRaw,
    DefaultColumnConstraint,
    DefinerProperty,
    Degrees,
    Delete,
    DenseRank,
    Describe,
    Detach,
    DictProperty,
    DictRange,
    DiToDate,
    Directory,
    DistKeyProperty,
    DistStyleProperty,
    DistributeBy,
    DistributedByProperty,
    Div,
    Dot,
    DotProduct,
    DropDatabase,
    DropFunction,
    DropIndex,
    DropNamespace,
    DropPartition,
    DropProcedure,
    DropSchema,
    DropSequence,
    DropTable,
    DropTrigger,
    DropType,
    DropView,
    DuplicateKeyProperty,
    ElementAt,
    Elt,
    Encode,
    EncodeProperty,
    Encrypt,
    EncryptRaw,
    EndsWith,
    EngineProperty,
    EnviromentProperty,
    Epoch,
    EpochMs,
    Eq,
    EqualNull,
    EuclideanDistance,
    Except,
    Execute,
    ExecuteAsProperty,
    Exists,
    Exp,
    Explode,
    ExplodeOuter,
    ExplodingGenerateSeries,
    Export,
    ExtendsLeft,
    ExtendsRight,
    ExternalProperty,
    Extract,
    FallbackProperty,
    FarmFingerprint,
    FeaturesAtTime,
    Fetch,
    FileFormatProperty,
    Filter,
    First,
    FirstValue,
    Float64,
    Floor,
    ForIn,
    ForeignKey,
    Format,
    FormatDate,
    FormatPhrase,
    FreespaceProperty,
    From,
    FromBase,
    FromTimeZone,
    FromUnixtime,
    Function,
    FunctionEmits,
    GapFill,
    Generate,
    GenerateDateArray,
    GenerateEmbedding,
    GenerateSeries,
    GenerateTimestampArray,
    GeneratedAsIdentityColumnConstraint,
    GeneratedAsRowColumnConstraint,
    Get,
    Getbit,
    GetExtract,
    Glob,
    Grant,
    GrantPrincipal,
    GrantPrivilege,
    Greatest,
    Group,
    GroupBy,
    GroupConcat,
    Grouping,
    GroupingId,
    GroupingSets,
    Gt,
    Gte,
    HashAgg,
    Having,
    HavingMax,
    Heredoc,
    Hex,
    HexEncode,
    HexStringExpr,
    Hint,
    HistoricalData,
    Hll,
    Hour,
    ILike,
    IfFunc,
    IfNull,
    Identifier,
    In,
    IncludeProperty,
    Index,
    IndexColumnConstraint,
    IndexConstraintOption,
    IndexParameters,
    IndexTableHint,
    Initcap,
    InOutColumnConstraint,
    InputModelProperty,
    InputOutputFormat,
    InheritsProperty,
    Insert,
    Install,
    Int64,
    IntDiv,
    Intersect,
    Interval,
    IntervalOp,
    IntervalSpan,
    IntoClause,
    Introducer,
    Is,
    IsFalse,
    IsInf,
    IsJson,
    IsNan,
    IsNull,
    IsTrue,
    IsolatedLoadingProperty,
    JSON,
    JSONArray,
    JSONArrayAgg,
    JSONArrayAppend,
    JSONArrayContains,
    JSONArrayInsert,
    JSONBContains,
    JSONBContainsAllTopKeys,
    JSONBContainsAnyTopKeys,
    JSONBDeleteAtPath,
    JSONBExists,
    JSONBExtract,
    JSONBExtractScalar,
    JSONBObjectAgg,
    JSONBool,
    JSONCast,
    JSONColumnDef,
    JSONExists,
    JSONExtract,
    JSONExtractArray,
    JSONExtractQuote,
    JSONExtractScalar,
    JSONFormat,
    JSONKeyValue,
    JSONKeys,
    JSONKeysAtDepth,
    JSONObject,
    JSONObjectAgg,
    JSONPath,
    JSONPathFilter,
    JSONPathKey,
    JSONPathRecursive,
    JSONPathRoot,
    JSONPathScript,
    JSONPathSelector,
    JSONPathSlice,
    JSONPathSubscript,
    JSONPathUnion,
    JSONRemove,
    JSONSchema,
    JSONSet,
    JSONStripNulls,
    JSONTable,
    JSONType,
    JSONValue,
    JSONValueArray,
    JarowinklerSimilarity,
    Join,
    JoinHint,
    JoinedTable,
    JournalProperty,
    JsonArray,
    JsonArrayAgg,
    JsonArrayLength,
    JsonExtract,
    JsonExtractPath,
    JsonExtractScalar,
    JsonInsert,
    JsonKeys,
    JsonMergePatch,
    JsonObject,
    JsonObjectAgg,
    JsonQuery,
    JsonRemove,
    JsonSet,
    JsonType,
    JsonValue,
    Kill,
    Lag,
    Lambda,
    LanguageProperty,
    Last,
    LastDay,
    LastValue,
    Lateral,
    LateralView,
    Lead,
    Least,
    Left,
    Length,
    Levenshtein,
    Like,
    LikeProperty,
    Limit,
    LimitOptions,
    List,
    ListAgg,
    Literal,
    Ln,
    LoadData,
    Localtime,
    Localtimestamp,
    LocationProperty,
    Lock,
    LockProperty,
    LockingProperty,
    LockingStatement,
    Log,
    LogProperty,
    LogicalAnd,
    LogicalOr,
    Lower,
    LowerHex,
    Lpad,
    LTrim,
    MLForecast,
    MLTranslate,
    MD5Digest,
    MD5NumberLower64,
    MD5NumberUpper64,
    MakeDate,
    MakeInterval,
    MakeTimestamp,
    ManhattanDistance,
    Map,
    MapCat,
    MapConcat,
    MapContainsKey,
    MapDelete,
    MapFromArrays,
    MapFromEntries,
    MapFunc,
    MapInsert,
    MapKeys,
    MapPick,
    MapValues,
    MaskingPolicyColumnConstraint,
    Match,
    MatchAgainst,
    MatchRecognize,
    MatchRecognizeMeasure,
    MaterializedProperty,
    Max,
    Median,
    MemberOf,
    Merge,
    MergeBlockRatioProperty,
    MergeTreeTTL,
    MergeTreeTTLAction,
    MethodCall,
    Min,
    Minhash,
    Minute,
    Mod,
    ModFunc,
    Mode,
    ModelAttribute,
    Month,
    MonthsBetween,
    Monthname,
    Mul,
    MultitableInserts,
    NTile,
    NamedArgument,
    NamedStruct,
    Neg,
    Neq,
    NextDay,
    NextValueFor,
    Normal,
    Normalize,
    Not,
    NotNullColumnConstraint,
    Ntile,
    Null,
    NullIf,
    Nullif,
    NullSafeEq,
    NullSafeNeq,
    NumberToStr,
    Nvl,
    Nvl2,
    NthValue,
    ObjectAgg,
    ObjectIdentifier,
    ObjectInsert,
    Offset,
    OnCluster,
    OnCommitProperty,
    OnCondition,
    OnConflict,
    OnProperty,
    Opclass,
    OpenJSON,
    OpenJSONColumnDef,
    Operator,
    OptionsProperty,
    Or,
    Ordered,
    OrderBy,
    OutputModelProperty,
    Over,
    OverflowTruncateBehavior,
    Overlaps,
    Overlay,
    Pad,
    Parameter,
    ParameterizedAgg,
    Paren,
    ParseDatetime,
    ParseIp,
    ParseJSON,
    ParseJson,
    ParseTime,
    ParseUrl,
    Partition,
    PartitionBoundSpec,
    PartitionByListProperty,
    PartitionByProperty,
    PartitionByRangeProperty,
    PartitionByRangePropertyDynamic,
    PartitionByTruncate,
    PartitionList,
    PartitionRange,
    PartitionedByBucket,
    PartitionedByProperty,
    PartitionedOfProperty,
    PathColumnConstraint,
    Percentile,
    PercentileCont,
    PercentileDisc,
    PercentRank,
    PeriodForSystemTimeConstraint,
    Pi,
    PipeOperator,
    Pivot,
    PivotAlias,
    PivotAny,
    Placeholder,
    Position,
    Power,
    Pragma,
    Prepare,
    PreWhere,
    Predict,
    PreviousDay,
    PrimaryKey,
    PrimaryKeyColumnConstraint,
    Prior,
    ProjectionDef,
    Properties,
    Property,
    PropertyEQ,
    Pseudocolumn,
    PseudoType,
    Put,
    Qualify,
    Quantile,
    Quarter,
    QueryBand,
    QueryOption,
    QueryTransform,
    RTrim,
    Radians,
    Rand,
    Random,
    Randn,
    Randstr,
    RangeBucket,
    RangeN,
    Rank,
    Raw,
    ReadCSV,
    ReadParquet,
    RecursiveWithSearch,
    Reduce,
    Reference,
    Refresh,
    RefreshTriggerProperty,
    RegexpCount,
    RegexpExtract,
    RegexpExtractAll,
    RegexpFullMatch,
    RegexpILike,
    RegexpInstr,
    RegexpLike,
    RegexpReplace,
    RegexpSplit,
    RegrAvgx,
    RegrAvgy,
    RegrCount,
    RegrIntercept,
    RegrR2,
    RegrSlope,
    RegrSxx,
    RegrSxy,
    RegrSyy,
    RegrValx,
    RegrValy,
    RemoteWithConnectionModelProperty,
    RenameColumn,
    Repeat,
    Replace,
    ReplacePartition,
    ReturnStmt,
    Returning,
    ReturnsProperty,
    Reverse,
    Revoke,
    Right,
    Rollback,
    Rollup,
    RollupProperty,
    Round,
    RowFormatDelimitedProperty,
    RowFormatProperty,
    RowFormatSerdeProperty,
    RowNumber,
    RowsFrom,
    Rpad,
    SHA,
    SHA1Digest,
    SHA2,
    SHA2Digest,
    SafeAdd,
    SafeCast,
    SafeDivide,
    SafeMultiply,
    SafeSubtract,
    SampleProperty,
    Schema,
    SchemaCommentProperty,
    ScopeResolution,
    Search,
    SearchIp,
    Second,
    SecurityProperty,
    Select,
    SemanticView,
    Sequence,
    SequenceProperties,
    SerdeProperties,
    SessionParameter,
    SessionUser,
    Set,
    SetConfigProperty,
    SetItem,
    SetOperation,
    SetProperty,
    SetStatement,
    SettingsProperty,
    SharingProperty,
    Show,
    Sign,
    SimilarTo,
    Sin,
    Skewness,
    Slice,
    SortArray,
    SortBy,
    SortKeyProperty,
    Soundex,
    Split,
    SplitPart,
    SplitTable,
    SqlComment,
    SqlReadWriteProperty,
    SqlSecurityProperty,
    Sqrt,
    StDistance,
    StPoint,
    StabilityProperty,
    StageReference,
    StandardHash,
    Star,
    StarMap,
    StartsWith,
    Stddev,
    StddevPop,
    StddevSamp,
    StorageHandlerProperty,
    StrPosition,
    StrToDate,
    StrToMap,
    StrToTime,
    StrToUnix,
    Stream,
    StringAgg,
    StringFunc,
    StringToArray,
    Struct,
    StructExtract,
    StructFunc,
    Stuff,
    Sub,
    Subquery,
    Subscript,
    Substring,
    SubstringIndex,
    Sum,
    SumIf,
    Summarize,
    Systimestamp,
    Table,
    TableAlias,
    TableArgument,
    TableFromRows,
    TableSample,
    Tag,
    Tags,
    Tan,
    TemporaryProperty,
    Time,
    TimeAdd,
    TimeDiff,
    TimeFromParts,
    TimeSlice,
    TimeStrToDate,
    TimeStrToTime,
    TimeStrToUnix,
    TimeSub,
    TimeToStr,
    TimeToUnix,
    TimeTrunc,
    TimeUnit,
    Timestamp,
    TimestampAdd,
    TimestampDiff,
    TimestampFromParts,
    TimestampSub,
    TimestampTrunc,
    TimestampTzFromParts,
    ToArray,
    ToBoolean,
    ToBinary,
    ToChar,
    ToDate,
    ToDecfloat,
    ToDouble,
    ToFile,
    ToJson,
    ToMap,
    ToNumber,
    ToTableProperty,
    ToTimestamp,
    Transaction,
    Transform,
    TransformKeys,
    TransformModelProperty,
    TransformValues,
    TransientProperty,
    Translate,
    TranslateCharacters,
    Trim,
    Truncate,
    TruncFunc,
    TruncateTable,
    TryCast,
    TryCatch,
    TryBase64DecodeBinary,
    TryBase64DecodeString,
    TryToDecfloat,
    TsMatch,
    TsOrDiToDi,
    TsOrDsAdd,
    TsOrDsDiff,
    TsOrDsToDate,
    TsOrDsToDatetime,
    TsOrDsToTime,
    TsOrDsToTimestamp,
    Tuple,
    Typeof,
    Uncache,
    Unhex,
    Unicode,
    UnicodeString,
    Uniform,
    Union,
    UniqueColumnConstraint,
    UniqueKeyProperty,
    UnixDate,
    UnixMicros,
    UnixMillis,
    UnixSeconds,
    UnixTimestamp,
    UnixToStr,
    UnixToTime,
    UnixToTimeStr,
    Unnest,
    Unpivot,
    UnpivotColumns,
    Update,
    Upper,
    Use,
    UserDefinedFunction,
    UsingData,
    UsingTemplateProperty,
    UtcTime,
    UtcTimestamp,
    Uuid,
    Values,
    Var,
    VarMap,
    VarPop,
    VarSamp,
    Variadic,
    Variance,
    VectorSearch,
    Version,
    ViewAttributeProperty,
    VolatileProperty,
    WatermarkColumnConstraint,
    Week,
    When,
    Whens,
    Where,
    WidthBucket,
    Window,
    WindowFunction,
    WindowSpec,
    With,
    WithDataProperty,
    WithFill,
    WithJournalTableProperty,
    WithOperator,
    WithProcedureOptions,
    WithSchemaBindingProperty,
    WithSystemVersioningProperty,
    WithTableHint,
    WithinGroup,
    XMLElement,
    XMLGet,
    XMLKeyValueOption,
    XMLTable,
    XmlNamespace,
    Xor,
    Year,
    YearOfWeek,
    YearOfWeekIso,
    Zipf,
    DateStrToDate,
    DateToDateStr,
)

format = format_sql
__version__ = _version()

__all__ = [
    "transpile",
    "parse",
    "parse_one",
    "parse_data_type",
    "generate",
    "qualify_tables",
    "rename_tables",
    "set_limit",
    "set_offset",
    "set_order_by",
    "format_sql",
    "format",
    "validate",
    "optimize",
    "analyze_query",
    "lineage",
    "lineage_at",
    "lineage_at_with_schema",
    "lineage_with_schema",
    "output_columns",
    "output_columns_with_schema",
    "source_tables",
    "openlineage_column_lineage",
    "openlineage_job_event",
    "openlineage_run_event",
    "diff",
    "tokenize",
    "dialects",
    "Expression",
    "PolyglotError",
    "ParseError",
    "GenerateError",
    "TranspileError",
    "ValidationError",
    "ColumnResolutionError",
    "ValidationResult",
    "ValidationErrorInfo",
    "__version__",
    # SQLGlot-compatible builder subset
    "select",
    "from_",
    "column",
    "col",
    "table_",
    "convert",
    "lit",
    "condition",
    "and_",
    "or_",
    "not_",
    "alias_",
    "func",
    "case",
    "update",
    "delete",
    "insert",
    "union",
    "intersect",
    "except_",
    # Key expression subclasses
    "Select",
    "Column",
    "Table",
    "Literal",
    "Identifier",
    "Star",
    "Alias",
    "Cast",
    "Function",
    "AggregateFunction",
    "WindowFunction",
    "From",
    "Join",
    "Where",
    "GroupBy",
    "Having",
    "OrderBy",
    "Limit",
    "With",
    "Cte",
    "Subquery",
    "Union",
    "Intersect",
    "Except",
    "Insert",
    "Update",
    "Delete",
    "TryCatch",
    "Prepare",
    "Execute",
    "Merge",
    "CreateTable",
    "DropTable",
    "AlterTable",
    "SplitTable",
    "FlashbackTable",
    "CreateView",
    "DropView",
    "And",
    "Or",
    "Not",
    "Eq",
    "In",
    "Between",
    "Like",
    "Case",
    "DataType",
    "Boolean",
    "Null",
    "Interval",
    "Array",
    "Struct",
    "Values",
    "Ordered",
    "Window",
    "Over",
    "Lambda",
    "Paren",
    "Count",
    "Sum",
    "Avg",
    "Min",
    "Max",
]
